# Generated by Django 6.0.4 on 2026-04-13 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mediafile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='mediafiles/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('filesize', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
