# Generated by Django 6.0.4 on 2026-04-13 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediaapp', '0002_auto_20260413_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediafile',
            name='filesize',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
